Makefile updated

diff --git a/ext/Makefile.inc b/ext/Makefile.inc
--- a/ext/Makefile.inc
+++ b/ext/Makefile.inc
@@ -18,7 +18,7 @@
 
 
 # version of this Makefile
-MAKEFILE_VER =			2.2
+MAKEFILE_VER :=			2.3
 
 # make options
 MAKEFLAGS +=			-s
@@ -31,30 +31,30 @@ MAKEFLAGS +=			-s
 # an example project is https://github.com/campisano/STSM/
 
 # # CUSTOM output executable and lib files
-# DEFAULT_TARGET =		debug
-# TARGET_EXEC =			stsm
-# TARGET_LIB =			libstsm.so
-# HEADER_EXT =			.hpp
-# SOURCE_EXT =			.cpp
+# DEFAULT_TARGET :=		debug
+# TARGET_EXEC :=		stsm
+# TARGET_LIB :=			libstsm.so
+# HEADER_EXT :=			.hpp
+# SOURCE_EXT :=			.cpp
 
 # # CUSTOM paths
-# INC_DIRS =			inc
-# INC_EXT_DIRS =		ext
-# FORMAT_INC_DIRS =		inc
-# SRC_DIRS =			src/stsm src/utils
-# TEST_SRC_DIRS =		src/tests
-# FORMAT_SRC_DIRS =		src
-# MAIN_SRC =			src/main.cpp
-# LIB_DIRS =			lib
-# ROOT_BUILD_DIR =		bin
+# INC_DIRS :=			include
+# INC_EXT_DIRS :=		ext
+# FORMAT_INC_DIRS :=		include
+# SRC_DIRS :=			src/stsm src/utils
+# TEST_SRC_DIRS :=		src/test
+# FORMAT_SRC_DIRS :=		src
+# MAIN_SRC :=			src/main.cpp
+# LIB_DIRS :=			lib
+# ROOT_BUILD_DIR :=		build
 
 # # CUSTOM libs for different targets
-# RELEASE_LIBS =
-# STATIC_LIBS =			$(RELEASE_LIBS)
-# LIBRARY_LIBS =		$(RELEASE_LIBS)
-# DEBUG_LIBS =			$(RELEASE_LIBS)
-# PROFILE_LIBS =		$(RELEASE_LIBS)
-# TEST_LIBS =			$(RELEASE_LIBS)
+# RELEASE_LIBS :=
+# STATIC_LIBS :=		$(RELEASE_LIBS)
+# LIBRARY_LIBS :=		$(RELEASE_LIBS)
+# DEBUG_LIBS :=			$(RELEASE_LIBS)
+# PROFILE_LIBS :=		$(RELEASE_LIBS)
+# TEST_LIBS :=			$(RELEASE_LIBS)
 
 # # finally, include the generic makefile
 # include ext/Makefile.inc
@@ -63,96 +63,94 @@ MAKEFLAGS +=			-s
 
 
 
-# obtaining list of include and lib dirs
-INC_DIRS :=			$(shell find $(INC_DIRS) -type d) $(INC_EXT_DIRS)                       # TODO check if empty
-INC_FLAGS :=			$(addprefix -I,$(INC_DIRS))
-LIB_DIRS :=			$(shell find $(LIB_DIRS) -type d)					# TODO check if empty
+# obtaining flags from defined list of dirs
+INC_FLAGS :=			$(addprefix -I,$(INC_DIRS) $(INC_EXT_DIRS))
 LIB_FLAGS :=			$(addprefix -L,$(LIB_DIRS))
 
 
 
 # compiler and linker binaries
-CXX =				g++
-LD =				g++
+CXX :=				g++
+LD :=				g++
 
-CPP_FLAGS =			$(INC_FLAGS) -MMD -MP
-CXX_FLAGS =			-pipe -std=c++11 -fexceptions -pedantic -Wall -Wextra
-LD_FLAGS =			$(LIB_FLAGS)
+CPP_FLAGS :=			$(INC_FLAGS) -MMD -MP
+CXX_FLAGS :=			-pipe -std=c++11 -fexceptions -pedantic -Wall -Wextra
+LD_FLAGS :=			$(LIB_FLAGS)
 
 
 
 # CUSTOM specific flags for different targets
-RELEASE_FLAGS =			-O3 -s									# optimization and remove all symbol table
-RELEASE_LD_FLAGS =
-STATIC_FLAGS =			$(RELEASE_FLAGS)
-STATIC_LD_FLAGS =		-static -static-libgcc -static-libstdc++ -pthread
-DEBUG_FLAGS =			-Og -ggdb -g3 -fno-omit-frame-pointer					# some debug optimization and increase debug level to 3, mantain frame pointer for 'prof' tool
-DEBUG_LD_FLAGS =
-PROFILE_FLAGS =			-g -pg									# add 'gprof' tool info
-PROFILE_LD_FLAGS =		-pg
-TEST_FLAGS =			$(DEBUG_FLAGS)
-TEST_LD_FLAGS =			$(DEBUG_LD_FLAGS)
-LIBRARY_FLAGS =			-fPIC
-LIBRARY_LD_FLAGS =		-shared
-#LIBRARY_LD_FLAGS =		-shared -Wl,-soname
+RELEASE_FLAGS :=		-O3 -s									# optimization and remove all symbol table
+RELEASE_LD_FLAGS :=
+STATIC_FLAGS :=			$(RELEASE_FLAGS)
+STATIC_LD_FLAGS :=		-static -static-libgcc -static-libstdc++
+DEBUG_FLAGS :=			-O0 -ggdb -g3 -fno-omit-frame-pointer					# disable optimization and increase debug level to 3, mantain frame pointer for 'prof' tool
+DEBUG_LD_FLAGS :=
+PROFILE_FLAGS :=		-g -pg									# add 'gprof' tool info
+PROFILE_LD_FLAGS :=		-pg
+TEST_FLAGS :=			$(DEBUG_FLAGS)
+TEST_LD_FLAGS :=		$(DEBUG_LD_FLAGS)
+LIBRARY_FLAGS :=		-fPIC
+LIBRARY_LD_FLAGS :=		-shared
+#LIBRARY_LD_FLAGS :=		-shared -Wl,-soname
 
 
 
 # defining existing targets
-TARGETS =			release static debug profile test library
-NODEPS_TARGETS =		clean
+TARGETS :=			release static debug profile test library
+NODEPS_TARGETS :=		clean
 
 
 
 # defining default target
 ifeq ($(MAKECMDGOALS),)
-	MAKECMDGOALS =		$(DEFAULT_TARGET)
+	MAKECMDGOALS :=		$(DEFAULT_TARGET)
 endif
 
 ifeq ($(MAKECMDGOALS), release)
-	TITLE =			Release build
-	BUILD_DIR =		$(ROOT_BUILD_DIR)/release
-	TARGET =		$(BUILD_DIR)/$(TARGET_EXEC)
-	SRCS :=			$(shell find $(SRC_DIRS) -name *$(SOURCE_EXT)) $(MAIN_SRC)
-	CXX_CMD_ARGS =		$(RELEASE_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
-	LD_CMD_ARGS =		$(RELEASE_FLAGS) $(RELEASE_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(RELEASE_LIBS))
+	TITLE :=		Release build
+	BUILD_DIR :=		$(ROOT_BUILD_DIR)/release
+	TARGET :=		$(BUILD_DIR)/$(TARGET_EXEC)
+	SRCS :=			$(shell find $(SRC_DIRS) $(MAIN_SRC) -type f -name \*$(SOURCE_EXT))
+	CXX_CMD_ARGS :=		$(RELEASE_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
+	LD_CMD_ARGS :=		$(RELEASE_FLAGS) $(RELEASE_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(RELEASE_LIBS))
 else ifeq ($(MAKECMDGOALS), static)
-	TITLE =			Static build
-	BUILD_DIR =		$(ROOT_BUILD_DIR)/static
-	TARGET =		$(BUILD_DIR)/$(TARGET_EXEC)
-	SRCS :=			$(shell find $(SRC_DIRS) -name *$(SOURCE_EXT)) $(MAIN_SRC)
-	CXX_CMD_ARGS =		$(STATIC_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
-	LD_CMD_ARGS =		$(STATIC_FLAGS) $(STATIC_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(STATIC_LIBS))
+	TITLE :=		Static build
+	BUILD_DIR :=		$(ROOT_BUILD_DIR)/static
+	TARGET :=		$(BUILD_DIR)/$(TARGET_EXEC)
+	SRCS :=			$(shell find $(SRC_DIRS) $(MAIN_SRC) -type f -name \*$(SOURCE_EXT))
+	CXX_CMD_ARGS :=		$(STATIC_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
+	LD_CMD_ARGS :=		$(STATIC_FLAGS) $(STATIC_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(STATIC_LIBS))
 else ifeq ($(MAKECMDGOALS), debug)
-	TITLE =			Debug build
-	BUILD_DIR =		$(ROOT_BUILD_DIR)/debug
-	TARGET =		$(BUILD_DIR)/$(TARGET_EXEC)
-	SRCS :=			$(shell find $(SRC_DIRS) -name *$(SOURCE_EXT)) $(MAIN_SRC)
-	CXX_CMD_ARGS =		$(DEBUG_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
-	LD_CMD_ARGS =		$(DEBUG_FLAGS) $(DEBUG_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(DEBUG_LIBS))
+	TITLE :=		Debug build
+	BUILD_DIR :=		$(ROOT_BUILD_DIR)/debug
+	TARGET :=		$(BUILD_DIR)/$(TARGET_EXEC)
+	SRCS :=			$(shell find $(SRC_DIRS) $(MAIN_SRC) -type f -name \*$(SOURCE_EXT))
+	CXX_CMD_ARGS :=		$(DEBUG_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
+	LD_CMD_ARGS :=		$(DEBUG_FLAGS) $(DEBUG_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(DEBUG_LIBS))
 else ifeq ($(MAKECMDGOALS), profile)
-	TITLE =			Profile build
-	BUILD_DIR =		$(ROOT_BUILD_DIR)/profile
-	TARGET =		$(BUILD_DIR)/$(TARGET_EXEC)
-	SRCS :=			$(shell find $(SRC_DIRS) -name *$(SOURCE_EXT)) $(MAIN_SRC)
-	CXX_CMD_ARGS =		$(PROFILE_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
-	LD_CMD_ARGS =		$(PROFILE_FLAGS) $(PROFILE_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(PROFILE_LIBS))
+	TITLE :=		Profile build
+	BUILD_DIR :=		$(ROOT_BUILD_DIR)/profile
+	TARGET :=		$(BUILD_DIR)/$(TARGET_EXEC)
+	SRCS :=			$(shell find $(SRC_DIRS) $(MAIN_SRC) -type f -name \*$(SOURCE_EXT))
+	CXX_CMD_ARGS :=		$(PROFILE_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
+	LD_CMD_ARGS :=		$(PROFILE_FLAGS) $(PROFILE_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(PROFILE_LIBS))
 else ifeq ($(MAKECMDGOALS), test)
-	TITLE =			Test build
-	BUILD_DIR =		$(ROOT_BUILD_DIR)/test
-	TARGET =		$(BUILD_DIR)/$(TARGET_EXEC)
-	SRCS :=			$(shell find $(SRC_DIRS) $(TEST_SRC_DIRS) -name *$(SOURCE_EXT))
-	CXX_CMD_ARGS =		$(TEST_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
-	LD_CMD_ARGS =		$(TEST_FLAGS) $(TEST_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(TEST_LIBS))
+	TITLE :=		Test build
+	BUILD_DIR :=		$(ROOT_BUILD_DIR)/test
+	TARGET :=		$(BUILD_DIR)/$(TARGET_EXEC)
+	SRCS :=			$(shell find $(SRC_DIRS) $(TEST_SRC_DIRS) -type f -name \*$(SOURCE_EXT))
+	CXX_CMD_ARGS :=		$(TEST_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
+	LD_CMD_ARGS :=		$(TEST_FLAGS) $(TEST_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(TEST_LIBS))
 else ifeq ($(MAKECMDGOALS), library)
-	TITLE =			Lib build
-	BUILD_DIR =		$(ROOT_BUILD_DIR)/lib
-	TARGET =		$(BUILD_DIR)/$(TARGET_LIB)
-	SRCS :=			$(shell find $(SRC_DIRS) -name *$(SOURCE_EXT))
-	CXX_CMD_ARGS =		$(LIBRARY_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
-	LD_CMD_ARGS =		$(LIBRARY_FLAGS) $(LIBRARY_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(LIBRARY_LIBS))
+	TITLE :=		Lib build
+	BUILD_DIR :=		$(ROOT_BUILD_DIR)/lib
+	TARGET :=		$(BUILD_DIR)/$(TARGET_LIB)
+	SRCS :=			$(shell find $(SRC_DIRS) -type f -name \*$(SOURCE_EXT))
+	CXX_CMD_ARGS :=		$(LIBRARY_FLAGS) $(CPP_FLAGS) $(CXX_FLAGS)
+	LD_CMD_ARGS :=		$(LIBRARY_FLAGS) $(LIBRARY_LD_FLAGS) $(LD_FLAGS) $(addprefix -l,$(LIBRARY_LIBS))
 else ifeq ($(MAKECMDGOALS), clean)
-	TITLE =			Clean
+	TITLE :=		Clean
 endif
 
 
@@ -168,42 +166,42 @@ DEPS :=				$(OBJS:.o=.d)
 
 ifeq ("$(PROGRAMFILES)$(ProgramFiles)","")
 # linux
-	SEPCHR =		/
+	SEPCHR :=		/
 # common binaries
-	MKDIR =			mkdir -p
-	RM =			rm -f
-	RMALL =			rm -rf
+	MKDIR :=		mkdir -p
+	RM :=			rm -f
+	RMALL :=		rm -rf
 # colors and terminal details
 # https://wiki.archlinux.org/index.php/Bash/Prompt_customization#Escapes_between_command_input_and_output
 # https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes
-	NORMAL =		"\\033[0;39m"
-	GREEN =			"\\033[1;32m"
-	WHITE =			"\\033[1;37m"
-	YELLOW =		"\\033[1;33m"
-	RED =			"\\033[1;31m"
-	BLUE =			"\\033[1;34m"
+	NORMAL :=		"\\033[0;39m"
+	GREEN :=		"\\033[1;32m"
+	WHITE :=		"\\033[1;37m"
+	YELLOW :=		"\\033[1;33m"
+	RED :=			"\\033[1;31m"
+	BLUE :=			"\\033[1;34m"
 else
-	SEPCHR =		\\\\
+	SEPCHR :=		\\\\
 ifneq (,$(findstring /cygdrive,$(PATH)))
 # cygwin
-	MKDIR =			mkdir -p
-	RM =			rm -f
-	RMALL =			rm -rf
+	MKDIR :=		mkdir -p
+	RM :=			rm -f
+	RMALL :=		rm -rf
 else ifneq (,$(findstring /mingw,$(PATH)))
 # mingw
-	MKDIR =			mkdir -p
-	RM =			rm -f
-	RMALL =			rm -rf
+	MKDIR :=		mkdir -p
+	RM :=			rm -f
+	RMALL :=		rm -rf
 else
 # windows
-	MKDIR =			md
-	RM =			del
-	RMALL =			rd /s /q
+	MKDIR :=		md
+	RM :=			del
+	RMALL :=		rd /s /q
 endif
 endif
 
 # check command results
-CHECK =				&& echo $(GREEN)"DONE"$(NORMAL) || (echo $(RED)"==== ERROR ===="$(NORMAL); exit 1)
+CHECK :=			&& echo $(GREEN)"DONE"$(NORMAL) || (echo $(RED)"==== ERROR ===="$(NORMAL); exit 1)
 
 
 
@@ -222,7 +220,21 @@ clean:				INFO_TRG
 	@echo Removing $(ROOT_BUILD_DIR) folder
 	$(if $(ROOT_BUILD_DIR),($(RMALL) $(ROOT_BUILD_DIR)),)
 
-.PHONY:				$(TARGETS) clean
+env:
+	echo INC_DIRS $(INC_DIRS)
+	echo INC_EXT_DIRS $(INC_EXT_DIRS)
+	echo FORMAT_INC_DIRS $(FORMAT_INC_DIRS)
+	echo SRC_DIRS $(SRC_DIRS)
+	echo TEST_SRC_DIRS $(TEST_SRC_DIRS)
+	echo FORMAT_SRC_DIRS $(FORMAT_SRC_DIRS)
+	echo MAIN_SRC $(MAIN_SRC)
+	echo LIB_DIRS $(LIB_DIRS)
+	echo ROOT_BUILD_DIR $(ROOT_BUILD_DIR)
+	echo
+	echo INC_FLAGS $(INC_FLAGS)
+	echo LIB_FLAGS $(LIB_FLAGS)
+
+.PHONY:				$(TARGETS) clean env
 
 # code style format target
 FORMAT:
@@ -231,10 +243,9 @@ FORMAT:
 --indent=spaces=4 --lineend=linux --align-pointer=middle \
 --pad-oper --pad-comma --unpad-paren \
 --add-brackets --convert-tabs --max-code-length=80 \
---suffix=none --recursive \
-$(FORMAT_INC_DIRS:%='%/*$(HEADER_EXT)') \
-$(FORMAT_SRC_DIRS:%='%/*$(SOURCE_EXT)') \
-|| true													# TODO check if FORMAT DIRS are empty
+--suffix=none \
+$(shell find $(FORMAT_INC_DIRS) $(FORMAT_SRC_DIRS) -type f \( -name \*$(HEADER_EXT) -o -name \*$(SOURCE_EXT) \)) \
+|| true
 
 
 
